In [1]:
#numpy 모듈 import
import numpy as np

In [2]:
#array() 함수: 파이썬 리스트 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능 수행
#ndarray.shape: ndarray의 차원과 크기를 튜플 형태로 나타냄
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [3]:
#ndarray.ndim: array의 차원을 나타냄
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
#ndarray내의 데이터값은 숫자, 문자열, 불 값 등 모두 가능
#ndarray내의 데이터 타입은 연산 특성상 같은 데이터 타입만 가능
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
#다른 데이터 유형이 섞여 있다면 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
#astype(): ndarray 내 데이터값의 타입 변경
#astype()에 인자로 원하는 타입을 문자열로 지정
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
#arange(): array를 range()로 표현하는 것
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
#zeros(): 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환
#ones(): 튜플 형태의 shape값을 입력하면 모든 값을 1으로 채운 해당 shape를 가진 ndarray 반환
#함수 인자로 dtype을 정해주지 않으면 디폴트로 float64형 데이터로 채움
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
#reshape(): ndarray를 특정 차원 및 크기로 변환
#지정된 사이즈로 변경이 불가능하면 오류 발생
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작 => array1[2]는 3번째 index 위치 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 2번째 값:',array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 맨 뒤에서 2번째 값: 8


In [13]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 값:', array2d[0,0])
print('(row=0, col=1) index 값:', array2d[0,1])
print('(row=1, col=0) index 값:', array2d[1,0])
print('(row=2, col=2) index 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 값: 1
(row=0, col=1) index 값: 2
(row=1, col=0) index 값: 4
(row=2, col=2) index 값: 9


In [14]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array1)
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [15]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [16]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [17]:
array1d = np.arange(start=1, stop=10)
#[] 안에 Boolean indexing 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과값:', array3)

array1d > 5 불린 인덱싱 결과값: [6 7 8 9]


In [19]:
#np.sort(): 원 행렬은 유지한 채 원 행렬의 정렬된 행렬 반환
#ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환, 반환 값=None
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬:', sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순 정렬: [9 5 3 1]


In [22]:
#행렬이 2차원 이상일 경우 axis 축 값 설정으로 정렬 수행 가능
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('low 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

low 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [24]:
#np.argsort(): 정렬된 행렬의 원본 행렬 인덱스 값 반환
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [25]:
#np.dot(): 행렬 내적(행렬 곱) 계산
A = np.array([[1,2,3],
              [4,5,6],])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [27]:
#transpose(): 원 행렬의 전치 행렬
A = np.array([[1,2],
              [3,4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
